In [3]:
import os
#path_Data = "/content/gdrive/MyDrive/VTCA/Datasets/" #Colab
path_Data = "D:\\MSE\\HomeWork\\Python\\Buoi3\\OnClass\\B\\Cross and Up Selling Problem\\" #Jupyter notebook
checkPath = os.path.isdir(path_Data)
checkFile = os.path.isfile(path_Data + "grocery_dataset.txt")
print("The path and file are valid or not :", checkPath, checkFile)

The path and file are valid or not : True True

In [1]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ImportError: DLL load failed while importing _cext: The specified module could not be found.

In [7]:
display("-".join(grocery_items))
print(len(grocery_items))

'long life bakery product-liver loaf-organic products-pastry-herbs-ice cream-pip fruit-specialty cheese-baking powder-domestic eggs-cling film/bags-butter milk-zwieback-light bulbs-meat spreads-flower (seeds)-flour-newspapers-baby food-chocolate-curd-waffles-citrus fruit-pot plants-frozen dessert-organic sausage-decalcifier-female sanitary products-curd cheese-frozen meals-pasta-male cosmetics-coffee-instant coffee-artif. sweetener-semi-finished bread-cocoa drinks-frozen fish-finished products-snack products-oil-specialty bar-salt-condensed milk-prosecco-frozen chicken-whipped/sour cream-preservation products-cereals-dessert-liquor-spread cheese-butter-bottled water-cooking chocolate-ham-roll products -soups-softener-brandy-beverages-dish cleaner-bags-processed cheese-white bread-beef-margarine-pickled vegetables-hair spray-sauces-seasonal products-sweet spreads-photo/film-skin care-detergent-sausage-napkins-white wine-abrasive cleaner-honey-hard cheese-whole milk-chicken-soft cheese-whisky-cake bar-specialty fat-rum-tropical fruit-candles-meat-brown bread-fruit/vegetable juice-cream cheese -syrup-nuts/prunes-berries-red/blush wine-canned beer-ketchup-frozen potato products-hygiene articles-soda-turkey-packaged fruit/vegetables-popcorn-other vegetables-yogurt-salad dressing-sound storage medium-spices-grapes-rubbing alcohol-canned fish-kitchen towels-chocolate marshmallow-canned vegetables-dog food-soap-house keeping products-rice-jam-tidbits-pork-bathroom cleaner-liqueur-salty snack-sparkling wine-specialty vegetables-Instant food products-shopping bags-mustard-mayonnaise-UHT-milk-frozen vegetables-candy-cream-frozen fruits-misc. beverages-cookware-vinegar-pet care-potato products-kitchen utensil-cleaner-baby cosmetics-rolls/buns-make up remover-sugar-cat food-ready soups-fish-pudding powder-chewing gum-toilet cleaner-dishes-onions-tea-nut snack-sliced cheese-frankfurter-hamburger meat-root vegetables-liquor (appetizer)-flower soil/fertilizer-bottled beer-canned fruit-specialty chocolate-dental care'

169

In [20]:
pip install --upgrade cycler python-dateutil pyparsing kiwisolver

Requirement already satisfied: cycler in c:\users\binhn\appdata\local\programs\python\python313\lib\site-packages (0.12.1)
Requirement already satisfied: python-dateutil in c:\users\binhn\appdata\local\programs\python\python313\lib\site-packages (2.9.0.post0)
Requirement already satisfied: pyparsing in c:\users\binhn\appdata\local\programs\python\python313\lib\site-packages (3.2.0)
Requirement already satisfied: kiwisolver in c:\users\binhn\appdata\local\programs\python\python313\lib\site-packages (1.4.7)
Requirement already satisfied: six>=1.5 in c:\users\binhn\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
output_list = list()
with open(path_Data + "grocery_dataset.txt") as f:
    reader = csv.reader(f, delimiter=",")
    for i, line in enumerate(reader):
        row_val = {item:0 for item in grocery_items}
        
        row_val.update({item:1 for item in line})
        output_list.append(row_val)

In [21]:
import matplotlib
print(matplotlib.__file__)

ImportError: DLL load failed while importing _cext: The specified module could not be found.

In [9]:
print(len(output_list), len(output_list[0]))
print(output_list[:5])

9835 169
[{'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 1, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 1, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 1, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 0, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 0, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 1, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 1, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 0, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 1, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 1, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 1, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 0, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 1, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 1, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 0, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 1, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 1, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 1, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 1, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 1, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 1, 'yogurt': 0, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}]

In [10]:
print(len(output_list), len(output_list[0]))
print(output_list[:5])

9835 169
[{'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 1, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 1, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 1, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 0, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 0, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 1, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 1, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 0, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 1, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 1, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 1, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 0, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 0, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 1, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 1, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 0, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 0, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 1, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 0, 'yogurt': 1, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}, {'long life bakery product': 1, 'liver loaf': 0, 'organic products': 0, 'pastry': 0, 'herbs': 0, 'ice cream': 0, 'pip fruit': 0, 'specialty cheese': 0, 'baking powder': 0, 'domestic eggs': 0, 'cling film/bags': 0, 'butter milk': 0, 'zwieback': 0, 'light bulbs': 0, 'meat spreads': 0, 'flower (seeds)': 0, 'flour': 0, 'newspapers': 0, 'baby food': 0, 'chocolate': 0, 'curd': 0, 'waffles': 0, 'citrus fruit': 0, 'pot plants': 0, 'frozen dessert': 0, 'organic sausage': 0, 'decalcifier': 0, 'female sanitary products': 0, 'curd cheese': 0, 'frozen meals': 0, 'pasta': 0, 'male cosmetics': 0, 'coffee': 0, 'instant coffee': 0, 'artif. sweetener': 0, 'semi-finished bread': 0, 'cocoa drinks': 0, 'frozen fish': 0, 'finished products': 0, 'snack products': 0, 'oil': 0, 'specialty bar': 0, 'salt': 0, 'condensed milk': 1, 'prosecco': 0, 'frozen chicken': 0, 'whipped/sour cream': 0, 'preservation products': 0, 'cereals': 0, 'dessert': 0, 'liquor': 0, 'spread cheese': 0, 'butter': 0, 'bottled water': 0, 'cooking chocolate': 0, 'ham': 0, 'roll products ': 0, 'soups': 0, 'softener': 0, 'brandy': 0, 'beverages': 0, 'dish cleaner': 0, 'bags': 0, 'processed cheese': 0, 'white bread': 0, 'beef': 0, 'margarine': 0, 'pickled vegetables': 0, 'hair spray': 0, 'sauces': 0, 'seasonal products': 0, 'sweet spreads': 0, 'photo/film': 0, 'skin care': 0, 'detergent': 0, 'sausage': 0, 'napkins': 0, 'white wine': 0, 'abrasive cleaner': 0, 'honey': 0, 'hard cheese': 0, 'whole milk': 1, 'chicken': 0, 'soft cheese': 0, 'whisky': 0, 'cake bar': 0, 'specialty fat': 0, 'rum': 0, 'tropical fruit': 0, 'candles': 0, 'meat': 0, 'brown bread': 0, 'fruit/vegetable juice': 0, 'cream cheese ': 0, 'syrup': 0, 'nuts/prunes': 0, 'berries': 0, 'red/blush wine': 0, 'canned beer': 0, 'ketchup': 0, 'frozen potato products': 0, 'hygiene articles': 0, 'soda': 0, 'turkey': 0, 'packaged fruit/vegetables': 0, 'popcorn': 0, 'other vegetables': 1, 'yogurt': 0, 'salad dressing': 0, 'sound storage medium': 0, 'spices': 0, 'grapes': 0, 'rubbing alcohol': 0, 'canned fish': 0, 'kitchen towels': 0, 'chocolate marshmallow': 0, 'canned vegetables': 0, 'dog food': 0, 'soap': 0, 'house keeping products': 0, 'rice': 0, 'jam': 0, 'tidbits': 0, 'pork': 0, 'bathroom cleaner': 0, 'liqueur': 0, 'salty snack': 0, 'sparkling wine': 0, 'specialty vegetables': 0, 'Instant food products': 0, 'shopping bags': 0, 'mustard': 0, 'mayonnaise': 0, 'UHT-milk': 0, 'frozen vegetables': 0, 'candy': 0, 'cream': 0, 'frozen fruits': 0, 'misc. beverages': 0, 'cookware': 0, 'vinegar': 0, 'pet care': 0, 'potato products': 0, 'kitchen utensil': 0, 'cleaner': 0, 'baby cosmetics': 0, 'rolls/buns': 0, 'make up remover': 0, 'sugar': 0, 'cat food': 0, 'ready soups': 0, 'fish': 0, 'pudding powder': 0, 'chewing gum': 0, 'toilet cleaner': 0, 'dishes': 0, 'onions': 0, 'tea': 0, 'nut snack': 0, 'sliced cheese': 0, 'frankfurter': 0, 'hamburger meat': 0, 'root vegetables': 0, 'liquor (appetizer)': 0, 'flower soil/fertilizer': 0, 'bottled beer': 0, 'canned fruit': 0, 'specialty chocolate': 0, 'dental care': 0}]

In [11]:
grocery_df = pd.DataFrame(output_list)

In [12]:
print(grocery_df.shape)
display(grocery_df.head())

(9835, 169)

,long life bakery product,liver loaf,organic products,pastry,herbs,ice cream,pip fruit,specialty cheese,baking powder,domestic eggs,...,sliced cheese,frankfurter,hamburger meat,root vegetables,liquor (appetizer),flower soil/fertilizer,bottled beer,canned fruit,specialty chocolate,dental care
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
# View top sold items
total_item_count = sum(grocery_df.sum())
print(total_item_count)
item_summary_df = grocery_df.sum().sort_values(ascending = False).reset_index().head(n=20)
item_summary_df.rename(columns={item_summary_df.columns[0]:'item_name',item_summary_df.columns[1]:'item_count'}, inplace=True)
item_summary_df.head()

43367

          item_name  item_count
0        whole milk        2513
1  other vegetables        1903
2        rolls/buns        1809
3              soda        1715
4            yogurt        1372

In [16]:
# Visualize top sold items
objects = (list(item_summary_df['item_name'].head(n=20)))
y_pos = np.arange(len(objects))
performance = list(item_summary_df['item_count'].head(n=20))

plt.figure(figsize=(20,5))
plt.bar(y_pos, performance, align='center', alpha=0.5, color ="navy")
plt.xticks(y_pos, objects, rotation='vertical',fontsize =28)
plt.yticks(fontsize =18)
plt.ylabel('Item count',fontsize =28)
plt.title('Item sales distribution',fontsize =28)

NameError: name 'plt' is not defined